[package]
name = "mtgatool-desktop"
version = "6.7.5"
description = "MTG Arena Tool Desktop"
authors = ["MTG Arena Tool"]
license = "MIT"
repository = "https://github.com/mtgatool/mtgatool-desktop"
edition = "2021"
rust-version = "1.70"

[build-dependencies]
tauri-build = { version = "1.5", features = [] }

[dependencies]
tauri = { version = "1.5", features = [
    "clipboard-all",
    "dialog-all",
    "fs-all",
    "global-shortcut-all",
    "notification-all",
    "path-all",
    "shell-open",
    "system-tray",
    "updater",
    "window-all"
] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
notify = "5.2"
tokio = { version = "1", features = ["full"] }
dirs = "5.0"
mtga-reader = { path = "../../mtga-reader", default-features = false }

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "s"
strip = true
