name: "Bump Version"

on:
  push:
    branches:
      - "master"

jobs:
  bump-version:
    name: Bump version (${{ github.sha }})
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v1"
        with:
          ref: ${{ github.ref }}

      - name: "cat package.json"
        run: cat ./package.json

      - name:  'Automated Version Bump'
        uses:  'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_EMAIL: 'mtgatool@gmail.com'
          GITHUB_USER: 'mtgatool-bot'
        with:
          tag-prefix:  'v'
          minor-wording:  'add,added,feat,feature,minor'
          major-wording:  'breaking'
          patch-wording:  'patch,fix,fixes,fixed'
          rc-wording:     'RELEASE'

      - name: "cat package.json"
        run: cat ./package.json
